# stage 1 Generate elysium-appd Binary
FROM golang:1.18-alpine as builder

RUN apk update && \
    apk upgrade && \
    apk --no-cache add make gcc musl-dev

ENV HOME /elysium-app

COPY / ${HOME}
WORKDIR ${HOME}

RUN make build

# stage 2
FROM alpine

RUN apk update && \
    apk upgrade && \
    apk --no-cache add curl jq bash

ENV HOME /elysium-app
COPY --from=builder ${HOME}/build/elysium-appd ${HOME}/elysium-appd
COPY docker/priv_validator_state.json ${HOME}/data/priv_validator_state.json
WORKDIR $HOME

# p2p, rpc and prometheus port
EXPOSE 26656 26657 1317 9090

# This allows us to always set the --home directory using an env 
# var while still capturing all arguments passed at runtime
ENTRYPOINT [ "/bin/bash", "-c", "exec ./elysium-appd \
            --home ${HOME} \
            \"${@}\"", "--" ]
# Default command to run if no arguments are passed
CMD ["--help"]
