[book]
authors = ["Elysium Labs"]
language = "en"
multilingual = false
src = "src"
title = "Elysium App Specifications"

[output.html]
git-repository-url = "https://github.com/furyaxyz/elysium-app"

[rust]
edition = "2021"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
